### ISSUE TITLE
Probably better to change event names

### ISSUE THREAD

**Issue by zxqfox** [andrewblond/bem-walk#5]
`data` event usually used for data chunk. But here you pushing not chunks but ready to use entities. Would be better to rename this to something like `entity`.

**Comment by andrewblond** [comment]
The event `data` is triggered if was found BEM-file on fs. Usually file is chunk of BEM-entity because complete BEM-entity consist of several files from several levels.

**Comment by zxqfox** [comment]
Let it be `data`. Thanks for answer!
